
node.name: node-1

discovery.type: single-node

network.host: 0.0.0.0
http.port: 9200

http.cors.enabled: true
http.cors.allow-origin: "*"

path.data: /usr/share/elasticsearch/data
path.logs: /var/log/elasticsearch

xpack.security.enabled: true
xpack.security.transport.ssl.enabled: false
