
server.host: "0.0.0.0"

xpack.monitoring.ui.container.elasticsearch.enabled: true

server.name: "my-kibana"

elasticsearch.hosts: ["http://elasticsearch:9200"]

elasticsearch.username: "kibana_system"
elasticsearch.password: "${KIBANA_SYSTEM_PASSWORD}"

server.ssl.enabled: false
